=== etourdot/xincproc/xinclude/src/spec/resources/XIncl20060927/testcases.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
    @(#)testcases.dtd   04/22/02
   
Typical use : 	<DOCTYPE test-suite SYSTEM "testcases.dtd">
Purpose:	To collect test cases for submission to the Xinclude Test Suite.


Elements:
	testsuite : 		This is the root element of the XInclude test suite. It is a collection of testcases from 
				various test suppliers.
	
	testcases:		This element should be the root element for an individual test collection. 

	contributor: 		This element can be used to name test contributors at the
				individual-person level.

	date: 			Date stamp on the testcase. Identifies date of creation or modification in the "qualifier" 
				argument.

	testcase: 		An individual test in the test collection. It should provide with the following elements;
				description, section, contributor, date and output

	section:		This element contains the resource argument to Point to the relevant sections in the specification. Provides a mechanism 
				for examining the description element.  Tests can apply to one or more particular SECTIONS.

	description:		Contains the test description, used to evaluate the diagnostic produced on negative
				tests. People will generally read this to evaluate whether the test failed for the 
				correct reasons (when applicable). This description will be used by the test system to be included in 
				the tables of test cases.
	
	output:			Output file (result-infoset) as expected by the submitter. This is an optional element 
				for informational purposes only. 

Attributes:
	creator:		This argument provides with the test collection originator.
	(tescases attribute)

	basedir:		This argument is the base directory in which tests for this collection reside.
            		
	href:			Test name or reference to an individual test.
	 			
	id:			
	("test-case" 
	attribute)		Unique identifier for each test case.

        features:		Any optional features that this test requires.
                                Implementations not supporting a feature should
				skip the test.  Values are:
		xpointer-scheme:     requires the xpointer scheme
		unexpanded-entities: requires the parser to not expand external
		                     entities
		unparsed-entities:   requires unparsed entity support
		lang-fixup:          requires xml:lang fixup support

	qualifier:		Indicates date of creation or modification of the test.

	resource:		Pointer to the applicable section of the specification.,
	("section" attribute)

	


		      	
-->
<!--The root element of the whole collection is test-suite and
    The root element of a collection should be "testcases". 
-->
<!ENTITY % URI "CDATA">
<!ENTITY % text "(#PCDATA | em | b | a)*">

<!ELEMENT testsuite (testcases+ )>
<!ELEMENT testcases (testcase | testresult)*>
<!ATTLIST testcases 	creator 	CDATA 		#IMPLIED
			basedir 	CDATA 		#IMPLIED>

<!ELEMENT testcase	(contributor,section+,date,description,output*)>
<!ATTLIST testcase 	id 		ID			#REQUIRED
			href		%URI;			#REQUIRED
			type	(success|error|optional)	#REQUIRED
			features        NMTOKENS                #IMPLIED>

<!ELEMENT description	(#PCDATA)>
<!ELEMENT section	(#PCDATA)>
<!ATTLIST section 	resource 	%URI; 		#REQUIRED>
<!ELEMENT contributor 	(#PCDATA)>



<!ELEMENT date	 	(#PCDATA)>
<!ATTLIST date qualifier (created|modified) "created">

<!ELEMENT output	(#PCDATA)>

<!--
    Really basic HTML font tweaks, to support highlighting
    some aspects of test descriptions ...
    EM == emphasis (e.g. italics, fun colors)
    B == bold
-->
<!ELEMENT em (#PCDATA | b)*>
<!ELEMENT b (#PCDATA | em)*>

<!-- 
    We also allow for hyperlinks in text (e.g., to include
    references to supporting evidence within SPECPROBLEM and 
    TESTPROBLEM).
-->
<!ELEMENT a (#PCDATA | b | em)*>
<!ATTLIST a
    href	%URI;				#REQUIRED
>

<!--
    The TESTRESULT element is used to record test results.
	It has a required ID attribute which identifies the TEST.
	It has a required AGREEMENT attribute that indicates whether
	the results are in full agreement with the expected
	results as described in the TEST case or not.

    The textual contents of the TESTRESULT element should describe
	the results of the test and any issues or further information.

    The target of the optional RESULTS attribute could be an XML Infoset

    The optional FUTURESUPPORT attribute is used to indicate
	expected future support of the feature tested by this
	test case.  

    The optional SPECPROBLEM attribute indicates if there is
	any ambiguity or other problem found in the spec that relates
	to this test.  Especially if the results weren't as expected
	because of a misinterpretation of the spec, this should be
	documented here.  Details/discussion should appear in the 
	textual contents of the TESTRESULT element.

    The optional TESTPROBLEM attribute indicates if there is
	any issue with the TEST case and the expected results it
	suggests.  Especially if the results of the test differ
	from that given as "expected" by the test case but are,
	in fact, believed to be the correct results, this should
	be documented here.  Details/discussion should appear in the 
	textual contents of the TESTRESULT element.

-->

<!ELEMENT testresult %text;>
<!ATTLIST testresult
    id		CDATA				#REQUIRED
    agreement	(full|issues)			#REQUIRED
    results		%URI;			#IMPLIED
    futuresupport	(full|partial|none)	#IMPLIED
    specproblem	(yes|no)		"no"
    testproblem	(yes|no)		"no"
>

=== etourdot/xincproc/xinclude/src/spec/resources/XIncl20060927/testdescr.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE testsuite SYSTEM "testcases.dtd" >
<testsuite>
	<testcases creator="Redhat" basedir="Imaq/test/XInclude/docs">
		<testcase id="imaq-include-xml-01" href="include.xml" type="success">
			<contributor>Daniel Veillard</contributor>
			<section resource="http://www.w3.org/TR/xinclude/#xml-included-items">4.2</section>
			<date qualifier="created">8-Mar-2002</date>
			<description>Simple test of including another XML document.</description>	
			<output>../../../result/XInclude/include.xml</output>
		</testcase>

		<testcase id="imaq-include-xml-02" href="recursive.xml" type="success">
			<contributor>Daniel Veillard</contributor>
			<section resource="http://www.w3.org/TR/xinclude/#loops">4.2.7</section>
			<date qualifier="created">8-Mar-2002</date>
			<description>Test recursive inclusion.</description>	
			<output>../../../result/XInclude/recursive.xml</output>
		</testcase>

		<testcase id="imaq-include-xml-03" href="nodes.xml" type="success" features="xpointer-scheme">
			<contributor>Daniel Veillard</contributor>
			<section resource="http://www.w3.org/TR/xinclude/#multiple-nodes">4.2.2</section>
			<date qualifier="created">8-Mar-2002</date>
			<description>Simple test of including a set of nodes from an XML document.</description>	
			<output>../../../result/XInclude/nodes.xml</output>
		</testcase>

		<testcase id="imaq-include-xml-04" href="docids.xml" type="success">
			<contributor>Daniel Veillard</contributor>
			<section resource="http://www.w3.org/TR/xinclude/#xml-included-items">4.2</section>
			<date qualifier="created">8-Mar-2002</date>
			<description>including another XML document with IDs</description>	
			<output>../../../result/XInclude/docids.xml</output>
		</testcase>

		<testcase id="imaq-include-xml-05" href="txtinclude.xml" type="success">
			<contributor>Daniel Veillard</contributor>
			<section resource="http://www.w3.org/TR/xinclude/#text-included-items">4.3</section>
			<date qualifier="created">8-Mar-2002</date>
			<description>Simple test of including another text document</description>	
			<output>../../../result/XInclude/txtinclude.xml</output>
		</testcase>

		<testcase id="imaq-include-xml-06" href="fallback.xml" type="success">
			<contributor>Daniel Veillard</contributor>
			<section resource="http://www.w3.org/TR/xinclude/#fallback">4.4</section>
			<date qualifier="created">21-Aug-2002</date>
			<description>Simple test of a fallback on unavailable URI.</description>	
			<output>../../../result/XInclude/fallback.xml</output>
		</testcase>
  <testcase id="imaq-pex1-01" href="pex1.xml" type="success">
   <!-- Transcribed by HST from http://lists.w3.org/Archives/Public/public-xml-core-wg/2006Aug/0033.html -->
   <contributor>Daniel Veillard</contributor>
   <section resource="http://www.w3.org/XML/2005/01/proposed-xinclude-errata#PEX1">3.2</section>
   <date qualifier="created">2006-09-27</date>
   <description>Unused fallbacks must not generate errors, even if broken.</description>
   <output>../../../result/XInclude/include.xml</output>
  </testcase>
  <testcase id="imaq-pex1-02" href="pex1a.xml" type="error">
   <contributor>Henry S. Thompson</contributor>
   <section resource="http://www.w3.org/XML/2005/01/proposed-xinclude-errata#PEX1">3.2</section>
   <date qualifier="created">2006-09-27</date>
   <description>Broken fallback must generate errors, if they're needed.</description>
  </testcase>
  <testcase id="imaq-pex6-03" href="pex6a.xml" type="success">
   <!-- Transcribed by HST from http://lists.w3.org/Archives/Public/public-xml-core-wg/2006Aug/0033.html -->
   <contributor>Daniel Veillard</contributor>
   <section resource="http://www.w3.org/XML/2005/01/proposed-xinclude-errata#PEX6">4.3</section>
   <date qualifier="created">2006-09-27</date>
   <description>A BOM in UTF16 is not added to the resulting document.</description>
   <output>../../../result/XInclude/pex6a.xml</output>
  </testcase>
  <testcase id="imaq-pex6-04" href="pex6b.xml" type="success">
   <!-- Transcribed by HST from http://lists.w3.org/Archives/Public/public-xml-core-wg/2006Aug/0033.html -->
   <contributor>Daniel Veillard</contributor>
   <section resource="http://www.w3.org/XML/2005/01/proposed-xinclude-errata#PEX6">4.3</section>
   <date qualifier="created">2006-09-27</date>
   <description>A BOM in UTF16LE is added to the resulting document.</description>
   <output>../../../result/XInclude/pex6b.xml</output>
  </testcase>
  <testcase id="imaq-pex11-05" href="pex11.xml" type="error">
   <!-- Transcribed by HST from http://lists.w3.org/Archives/Public/public-xml-core-wg/2006Aug/0033.html -->
   <contributor>Daniel Veillard</contributor>
   <section resource="http://www.w3.org/XML/2005/01/proposed-xinclude-errata#PEX11">3.1</section>
   <date qualifier="created">2006-09-27</date>
   <description>'accept' attributes with characters outside the range #x20 through #x7E must
    be flagged as fatal errors.</description>
  </testcase>
	</testcases>
	<testcases creator="FourThought" basedir="FourThought/test/XInclude/docs">
		<testcase id="FourThought-include-01" href="ft-include1.xml" type="success">
			<contributor>John Evdemon</contributor>
			<section resource="http://www.w3.org/TR/xinclude/#syntax">3.1</section>
			<date qualifier="created">18-September-2002</date>
			<description>Simple test of including another XML document.</description>	
			<output>../../../result/XInclude/include1.xml</output>
		</testcase>
		
		<testcase id="FourThought-include-02" href="ft-include2.xml" type="success">
			<contributor>John Evdemon</contributor>
			<section resource="http://www.w3.org/TR/xinclude/#loops">4.2.7</section>
			<date qualifier="created">18-September-2002</date>
			<description>Test recursive inclusion.</description>	
			<output>../../../result/XInclude/include2.xml</output>
		</testcase>

		
		<testcase id="FourThought-include-03" href="ft-include3.xml" type="success">
			<contributor>John Evdemon</contributor>
			<section resource="http://www.w3.org/TR/xinclude/#syntax">3.1</section>
			<date qualifier="created">18-September-2002</date>
			<description>Simple test of including another text document.</description>	
			<output>../../../result/XInclude/include3.xml</output>
		</testcase>

		<testcase id="FourThought-include-04" href="ft-include4.xml" type="success" features="xpointer-scheme">
			<contributor>John Evdemon</contributor>
			<section resource="http://www.w3.org/TR/xinclude/#multiple-nodes">4.2.2</section>
			<date qualifier="created">18-September-2002</date>
			<description>Simple test of including a set of nodes from an XML document.</description>	
			<output>../../../result/XInclude/include4.xml</output>
		</testcase>

		<testcase id="FourThought-include-05" href="ft-include5.xml" type="success" features="xpointer-scheme">
			<contributor>John Evdemon</contributor>
			<section resource="http://www.w3.org/TR/xinclude/#multiple-nodes">4.2.2</section>
			<date qualifier="created">18-September-2002</date>
			<description>Simple test of including a set of nodes from an XML document.</description>	
			<output>../../../result/XInclude/include5.xml</output>
		</testcase>

		<testcase id="FourThought-include-06" href="ft-include6.xml" type="success" features="xpointer-scheme">
			<contributor>John Evdemon</contributor>
			<section resource="http://www.w3.org/TR/xinclude/#docii">4.2.1</section>
			<date qualifier="created">18-September-2002</date>
			<description>Simple test of including a set of nodes from an XML document.</description>	
			<output>../../../result/XInclude/include6.xml</output>
		</testcase>

		<testcase id="FourThought-include-07" href="ft-include7.xml" type="success" features="xpointer-scheme">
			<contributor>John Evdemon</contributor>
			<section resource="http://www.w3.org/TR/xinclude/#elements">4.2.5</section>
			<date qualifier="created">18-September-2002</date>
			<description>Simple test of including a set of nodes from an XML document.</description>	
			<output>../../../result/XInclude/include7.xml</output>
		</testcase>
		
	</testcases>

	<testcases creator="NIST" basedir="Nist/test/docs">
		<testcase id="Nist-include-01" href="nist-include-01.xml" type="success">
			<contributor>Sandra I. Martinez</contributor>
			<section resource="http://www.w3.org/TR/xinclude/#syntax">3.1</section>
			<date qualifier="created">18-September-2002</date>
			<description>Test the inclusion of  another XML document.</description>	
			<output>../../result/nist-include-01.xml</output>
		</testcase>

		<testcase id="Nist-include-02" href="nist-include-02.xml" type="success">
			<contributor>Sandra I. Martinez</contributor>
			<section resource="http://www.w3.org/TR/xinclude/#syntax">3.1</section>
			<date qualifier="created">September-2002</date>
			<description>Test that the encoding attribute in the Xinclude element has no effect when parse="xml".</description>	
			<output>../../result/nist-include-02.xml</output>
		</testcase>

		<testcase id="Nist-include-03" href="nist-include-03.xml" type="error">
			<contributor>Sandra I. Martinez</contributor>
			<section resource="http://www.w3.org/TR/xinclude/#syntax">3.1</section>
			<date qualifier="created">September, 2002</date>
			<description>Test that values other than xml or text, in the parse attribute of the XInclude 
				element, result in fatal errors. </description>	
		</testcase>

		<testcase id="Nist-include-04" href="nist-include-04.xml" type="success">
			<contributor>Sandra I. Martinez</contributor>
			<section resource="http://www.w3.org/TR/xinclude/#syntax">3.2</section>
			<date qualifier="created">September, 2002</date>
			<description>Test of fallback element appearing as a child of an xinclude element. </description>	
			<output>../../result/nist-include-04.xml</output>
		</testcase>

		<testcase id="Nist-include-05" href="nist-include-05.xml" type="error">
			<contributor>Sandra I. Martinez</contributor>
